import Animater from "./components/Animater";
import Footer from "./components/Footer";
import Heading from "./components/Heading";
import "./globals.css";
import { Inter, Poppins, Open_Sans, Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const open = Open_Sans({ subsets: ["latin-ext"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["500", "200"] });
const monserat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Citywidelondon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      
          <Heading />
          {children}
          <Footer />{" "}
    
      </body>
    </html>
  );
}
